// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqGaH8yuvPZXhVFo8FzUwt4flYRteFkpo',
    appId: '1:607021416060:web:caeb479aa4c49fd87353f9',
    messagingSenderId: '607021416060',
    projectId: 'techassist-7b790',
    authDomain: 'techassist-7b790.firebaseapp.com',
    storageBucket: 'techassist-7b790.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxcAxwInX5bDK4-l86ai8CPkRIn4HQQh0',
    appId: '1:607021416060:android:070e82eb7c1252017353f9',
    messagingSenderId: '607021416060',
    projectId: 'techassist-7b790',
    storageBucket: 'techassist-7b790.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfCja1PXyXQXD3rzwkjwnZJ7vfuSWJIfk',
    appId: '1:607021416060:ios:e6ec446c3f23e71e7353f9',
    messagingSenderId: '607021416060',
    projectId: 'techassist-7b790',
    storageBucket: 'techassist-7b790.appspot.com',
    iosBundleId: 'com.example.techassistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfCja1PXyXQXD3rzwkjwnZJ7vfuSWJIfk',
    appId: '1:607021416060:ios:c1f8707467c054ec7353f9',
    messagingSenderId: '607021416060',
    projectId: 'techassist-7b790',
    storageBucket: 'techassist-7b790.appspot.com',
    iosBundleId: 'com.example.techassistApp.RunnerTests',
  );
}
